spring.application.name=quantitymeasurement

spring.datasource.url=jdbc:mysql://quantitymeasurementdb:3306/qm_db
spring.datasource.username=quantityadmin
spring.datasource.password=Quantity@123

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

#logging.level.root=debug
logging.file.name=app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} -- %level -- %logger{36} -- %msg%n